### ISSUE TITLE
TypeError: items.forEach is not a function

### ISSUE THREAD

**Issue by fallenturtle** [EvanLovely/scss-to-json#2]
Any idea what I might be doing wrong if I'm getting this error?

> TypeError: items.forEach is not a function
>     at compile (/Users/abailey/Downloads/edition-node-gulp-1.3-1.4/node_modules/scsstojson/index.js:6:9)
>     at PatternLabEventEmitter.addScssToJsonData (/Users/abailey/Downloads/edition-node-gulp-1.3-1.4/node_modules/plugin-node-scsstojson/index.js:13:3)
>     at PatternLabEventEmitter.emit (events.js:182:13)
>     at PatternLabEventEmitter.EventEmitter.emit (domain.js:442:20)
>     at buildPatterns (/Users/abailey/Downloads/edition-node-gulp-1.3-1.4/node_modules/patternlab-node/core/lib/patternlab.js:539:23)
>     at Object.build (/Users/abailey/Downloads/edition-node-gulp-1.3-1.4/node_modules/patternlab-node/core/lib/patternlab.js:622:7)
>     at build (/Users/abailey/Downloads/edition-node-gulp-1.3-1.4/gulpfile.js:127:14)
>     at bound (domain.js:396:14)
>     at runBound (domain.js:409:12)
>     at asyncRunner (/Users/abailey/Downloads/edition-node-gulp-1.3-1.4/node_modules/async-done/index.js:55:18)

**Comment by fallenturtle** [comment]
More info:
I'm using a Mac. Node version 10.7, gulp v4.0.0-alpha.3.
This is with the Gulp version of Pattern Lab node v1.3.4.

I'm also trying to use this with plugin-node-scsstojson.

From my patternlab-config.json:

> "plugins": {
>     "plugin-node-scsstojson": {
>       "enabled": true,
>       "initialized": false,
>       "options": {
>         "scssFiles": {
>           "src": "source/css/scss/base/_colors.scss",
>           "dest": "source/_patterns/00-atoms/00-global/colors.json",
>           "lineStartsWith": "$color-",
>           "allowVarValues": false
>         }
>       }
>     }
>   }
